### ISSUE TITLE
Connection failing in startup.cs

### ISSUE THREAD

**Issue by ms-mansisinghal** [Azure/Microsoft.Azure.StackExchangeRedis#12]
Hi, 

I am trying the following code in my startup.cs to make the connection for redis cache but it isn't working for me. 

```   

            services.AddStackExchangeRedisCache(async options =>
            {
             
                 var configurationOptions = await ConfigurationOptions.Parse($"{CacheName}:6380").ConfigureForAzureWithSystemAssignedManagedIdentityAsync(principalID);
                 options.ConfigurationOptions = configurationOptions;
                 var connectionMultiplexer = ConnectionMultiplexer.ConnectAsync(configurationOptions);
                
                options.InstanceName = Constants.UserManagementService;

            });
```
            
 Can someone provide a sample for this or managed identity in startup.cs

**Comment by lsannicolas** [comment]
Hello, could you update with the error and where you're running the startup.cs? Connecting with AAD is only supported on Azure VMs for now.

**Comment by ms-mansisinghal** [comment]
Hey, we are trying to connect our Reddis cache to an Azure App service. Is that possible?

**Comment by sven5** [comment]
It seems this library does not work together with ASP.NET Core's `Microsoft.Extensions.Caching.StackExchangeRedis` extensions. Is there anything in progress to get this working?
@eerhardt @philon-msft

**Comment by eerhardt** [comment]
cc @mgravell

**Comment by philon-msft** [comment]
The extension built out of this repo is only for the `StackExchange.Redis` library itself. To request AAD support for `Microsoft.Extensions.Caching.StackExchangeRedis`, I'd recommend creating an issue in the https://github.com/dotnet/aspnetcore repo.

**Comment by RichFinn-WTW** [comment]
> It seems this library does not work together with ASP.NET Core's `Microsoft.Extensions.Caching.StackExchangeRedis` extensions. Is there anything in progress to get this working? @eerhardt @philon-msft
> 
> Please show a sample using ASP.NET Core Web App.

@sven5 - we were able to get `Microsoft.Azure.StackExchangeRedis` working with `Microsoft.Extensions.Caching.StackExchangeRedis`, adding Entra auth to our Redis resources

Extension method:

```cs
﻿
public static class CachingExtensions
{
    public static async Task<IServiceCollection> AddCaching(this IServiceCollection services, IConfiguration configuration)
    {
        services.Configure<CachingOptions>(configuration.GetSection(CachingOptions.Position));
        var settings = configuration.GetSection(CachingOptions.Position).Get<CachingOptions>(); 
        
        var configurationOptions = ConfigurationOptions.Parse(settings.RedisConnectionString);
        await configurationOptions.ConfigureForAzureWithTokenCredentialAsync(new DefaultAzureCredential());
        configurationOptions.DefaultDatabase = settings.RedisDefaultDatabase;
        
        services.AddStackExchangeRedisCache(options =>
        {
            options.ConfigurationOptions = configurationOptions;
        });       

        return services;
    }
}
```

Program.cs (minimal):

```cs 
var builder = WebApplication.CreateBuilder(args);

await builder.Services.AddCaching(builder.Configuration);
```

**Comment by yannic-hamann-abb** [comment]
To reuse the connection pool (`ConnectionMultiplexer`) I do the following:

``` csharp
var lazyMultiplexer = new Lazy<IConnectionMultiplexer>(() =>
{
    using var writer = File.AppendText(Path.Combine(Path.GetTempPath(), "redis_connection.log"));
    writer.AutoFlush = true;
    return ConnectionMultiplexer.Connect(builder.Configuration.GetRequiredConnectionString("Redis"), writer);
});

services.AddStackExchangeRedisCache(options =>
{
    options.ConnectionMultiplexerFactory = () => Task.FromResult(lazyMultiplexer.Value);
});

// probably want the same connection multiplexer for your health checks too:
builder.Services.AddSingleton(sp =>
{
    return lazyMultiplexer.Value;
});

services
    .AddHealthChecks()
    .AddRedis(sp => sp.GetRequiredService<IConnectionMultiplexer>(), tags: ["ready"]);

```
