### ISSUE TITLE
Support ServicePrinciple with Token to create Redis ConnectionMultiplexer

### ISSUE THREAD

**Issue by AdamWuGitHub** [Azure/Microsoft.Azure.StackExchangeRedis#13]
In Private review, Azure Redis support service principal with AccessToken, can we keep support that in the new lib?

ConfigurationOptions options = ConfigurationOptions.Parse($"{HostName}:6380,user={ServicePrincipalName},password={result.AccessToken}");

**Comment by samsaha-ms** [comment]
From public preview onwards server-side authentication check is hardened. Additionally multiple SPN can share the same name. Based on these factors and feedback from private preview customers we have removed the support for SPN name from server side itself. Hence for this client library it is irrelevant now to support.

**Comment by AdamWuGitHub** [comment]
Can we support using certificate to authorize AAD?

**Comment by samsaha-ms** [comment]
I believe active work is ongoing to support certificate based auth using SPN.
@philon-msft, do you want to take this question?

**Comment by philon-msft** [comment]
v2.0.0 supports authentication using a Service Principal certificate. Please let us know if you see any issues.
