### ISSUE TITLE
ConfigureForAzureWithUserAssignedManagedIdentityAsync() not working with Microsoft.Identity.Client 4.54.1

### ISSUE THREAD

**Issue by mirjana1211** [Azure/Microsoft.Azure.StackExchangeRedis#18]
I am connecting to Redis from Azure AppService using user assigned identity. After adding Azure.Identity (1.10.0) nuget package to the same project, I have started receiving the following error when calling ConfigureForAzureWithUserAssignedManagedIdentityAsync:

System.MissingMethodException: 'Method not found: 'Microsoft.Identity.Client.ManagedIdentityApplicationBuilder Microsoft.Identity.Client.ManagedIdentityApplicationBuilder.Create(System.String)'.'

I could verify that the issue does not occur witht and older version of Microsoft.IdentityClient. In my case, the installation of Azure.Identity raised the version of Microsoft.Identity.Client from 4.53.0 to 4.54.1.

**Comment by mcraiha** [comment]
Same happens with `ConfigureForAzureWithSystemAssignedManagedIdentityAsync`, but at least in my case Azure.Identity (1.9.0) works correctly.

**Comment by tompazourek** [comment]
@philon-msft Can you please release the latest version of this packge that includes #7?

**Comment by tompazourek** [comment]
A month has passed, and still nothing has changed. This is now a more serious issue as there's a CVE in Azure.Identity (https://github.com/advisories/GHSA-5mfx-4wcx-rv27) which also relates to these package versions...

**Comment by tompazourek** [comment]
All that needs to happen is to take the current code that's already `master` since June and release it as package 1.1.1 or 1.2.0.

Maybe @lsannicolas can help with this?

The CVE in Azure.Identity forces an update of "Microsoft.Identity.Client" to version incompatible with "Microsoft.Azure.StackExchangeRedis".

**Comment by sigurdmwahl** [comment]
I am also experiencing this issue and waiting for this to be resolved.

**Comment by philon-msft** [comment]
The new release v2.0.0 uses the latest Microsoft.Client.Identity package. Please give it a try and let us know if you still see any issues.
