### ISSUE TITLE
Not able to debug locally when trying to system-assigned managed identity or user-assigned managed identity

### ISSUE THREAD

**Issue by rapr04** [Azure/Microsoft.Azure.StackExchangeRedis#19]
I need to implement "user-assigned managed identity" to access the redis cache. This is working perfectly on the Azure, but how to debug locally, as DefaultAzureCredential is not available so not able to run from Visual Studio Login account. Is there any suggestion to solve local debugging issue?

**Comment by lsannicolas** [comment]
We do have plan to support the DefaultAzureCredential in the upcoming release. As of right now we do not have a way to debug locally on a non-azure vm with this extension

**Comment by rapr04** [comment]
Hi, our development  environment is non-azure vm. Is there any timeline by when we would have DefaultAzureCredential  implemented?

**Comment by lsannicolas** [comment]
We are working on getting the PR merged, so it should be included in the next release. Unfortunately, we don't have an exact date for the next release set yet.

**Comment by rapr04** [comment]
Thanks for the response. Eagerly waiting for DefaultAzureCredential
