### ISSUE TITLE
Authentication with  System Assigned Identity not working 

### ISSUE THREAD

**Issue by devesh1207** [Azure/Microsoft.Azure.StackExchangeRedis#34]
I am getting this error when using authentication with system managed identity:

        "message": "Method not found: 'Microsoft.Identity.Client.ManagedIdentityApplicationBuilder Microsoft.Identity.Client.ManagedIdentityApplicationBuilder.Create(System.String)'."

I even downgraded the Microsoft.Identity.Client to version 4.53.0

**Comment by philon-msft** [comment]
The new release v2.0.0 uses the latest Microsoft.Identity.Client package. Please give it a try and let us know if you still see any issues.
