### ISSUE TITLE
lifetime of multiplexer

### ISSUE THREAD

**Issue by eddynaka** [Azure/Microsoft.Azure.StackExchangeRedis#36]
Hello!

With the recent change that adds support for DefaultAzureCredentials, I would like to understand if the connectionMultiplexer is still safe to be a singleton or if this should be created per request, for example.

This is the snippet that I'm referring to:
```csharp
var configurationOptions = await ConfigurationOptions.Parse($"{cacheHostName}:6380").ConfigureForAzureWithTokenCredentialAsync(username!, new DefaultAzureCredential());
var connectionMultiplexer = await ConnectionMultiplexer.ConnectAsync(configurationOptions);

```

**Comment by philon-msft** [comment]
ConnectionMultiplexer instances should always be long-lived singletons. A connection should be created during startup of a client app instance, and then reused for all commands executed on a cache for the lifetime of the app instance. Creating new connections imposes a large delay and increased server load on Redis, so creating and closing connections should be kept to a minimum. 

StackExchange.Redis will take care of recovering the connection if there are any transient disruptions, and the code in this extension package will ensure that the connection's authentication token kept current for the lifetime of the connection.

**Comment by eddynaka** [comment]
Nice!
Thanks for explaining that everything will be handled internally!

Feel free to close!
