### ISSUE TITLE
CS8002 Error: assembly Microsoft.Azure.StackExchangeRedis does not have a strong name

### ISSUE THREAD

**Issue by jayshims** [Azure/Microsoft.Azure.StackExchangeRedis#4]
Looks like the package is not strong name signed.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS8002	Referenced assembly 'Microsoft.Azure.StackExchangeRedis, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

![image](https://github.com/Azure/Microsoft.Azure.StackExchangeRedis/assets/92951754/6fb2cf69-d29b-4bfb-bf8a-b03b8e5a4edc)

**Comment by philon-msft** [comment]
Thanks for reporting this @jayshims. We're working on a new release that will be fully signed.

**Comment by adamnova** [comment]
Is there any update for this issue @philon-msft?

**Comment by philon-msft** [comment]
No update yet - the next release will be fully signed

**Comment by philon-msft** [comment]
The Microsoft.Azure.StackExchangeRedis.dll assembly is now strong name signed in v2.0.0. Please give it a try and let us know if any issues remain.
