### ISSUE TITLE
Connection Reauthentication always fails

### ISSUE THREAD

**Issue by a99cl208** [Azure/Microsoft.Azure.StackExchangeRedis#51]
Hello,

Package v3.0.0 introducted the GetUserName function here: https://github.com/Azure/Microsoft.Azure.StackExchangeRedis/blob/main/src/AzureCacheOptions.cs#L81
Which is used to assign the `User` property on the `ConfigurationOptions` here: https://github.com/Azure/Microsoft.Azure.StackExchangeRedis/blob/main/src/AzureCacheForRedis.cs#L116

However, the function is not used to override the `User` property of the `AzureOptionsProvider` base class of `AzureCacheOptionsProviderWithToken`
which is assigned to ConfigurationOptions.Default here: https://github.com/Azure/Microsoft.Azure.StackExchangeRedis/blob/main/src/AzureCacheForRedis.cs#L115

As a consequence, when the reauthentication is done here: https://github.com/Azure/Microsoft.Azure.StackExchangeRedis/blob/main/src/AzureCacheOptionsProviderWithToken.cs#L241
The `User` property passed is `null` because not overridden (as it was in v2.0.0 of the package). 

This makes the execution failed systematically, with error "ERR protocol error: invalid bulk length".

To solve this bug, you have to override the User property inside the `AzureCacheOptionsProviderWithToken` class, and assign its value from the GetUserName function of the `AzureCacheOptions`

**Comment by philon-msft** [comment]
Hi @a99cl208 thanks for the detailed bug report. Please take a look at PR #52

**Comment by a99cl208** [comment]
Looks good to me!

**Comment by philon-msft** [comment]
Fixed in PR #52. Version 3.1.0 including this fix will be released shortly. Thanks for your feedback!
