### ISSUE TITLE
Configurable audiences in client

### ISSUE THREAD

**Issue by KirilNN** [Azure/Microsoft.Azure.StackExchangeRedis#60]
Hello everybody,

In the current implementation of the client there is a hardcoded claim for the AcquireTokenForManagedIdentity flow, in case someone would like to reuse the client with our own version of Redis implementation in Azure and still leveraging Microsoft Managed Identity, it would be nice to be able to override the claim or add custom ones. Would you be open to accepting such contribution to the codebase?

**Comment by philon-msft** [comment]
Thanks for the suggestion @KirilNN 
Please take a look at PR #67

**Comment by philon-msft** [comment]
The `AzureCacheOptions.Scope` field is now available in v3.2.0
