### ISSUE TITLE
Authenticating Azure Redis Cache with User Assigned Managed Identity in .NET 8 and C# 12

### ISSUE THREAD

**Issue by santoshpatro** [Azure/Microsoft.Azure.StackExchangeRedis#61]
Hi Team,

Need help on the implementation with some code sample using .NET 8 and C#12 for the issue : How can we determine when the token has expired, and how can the client execute a Redis AUTH command automatically before the Microsoft Entra token expires. https://stackoverflow.com/questions/78869325/authenticating-azure-redis-cache-with-user-assigned-managed-identity-in-net-8-a

Can anyone help me here with some code sample which will serve as a reference for my implementation?

Thanks,
Santosh

**Comment by philon-msft** [comment]
Read the README: https://github.com/Azure/Microsoft.Azure.StackExchangeRedis
