### ISSUE TITLE
Dependency on Azure.Identity Version 1.12.0 which contains bug

### ISSUE THREAD

**Issue by YotamEN** [Azure/Microsoft.Azure.StackExchangeRedis#63]
This package uses Azure.Identity Version 1.12.0 which contains a bug causing timeouts while trying to authenticate with Azure resources.
You should use an older version / check if they have fixed and provided a newer version.

See https://github.com/Azure/azure-sdk-for-net/issues/44817

**Comment by YotamEN** [comment]
Link to dependency: https://github.com/Azure/Microsoft.Azure.StackExchangeRedis/blame/a1a4bef386ba3fd7ca38f36ea38b20da8f10bced/Directory.Packages.props#L5

**Comment by isacruzramos** [comment]
Its the azure.core 1.40 that has the bug, not the Azure.Identity 1.12 correct?

**Comment by isacruzramos** [comment]
@YotamEN this is the bug in Azure.Core 1.40 that causes time outs as token refreshes:
https://github.com/Azure/azure-sdk-for-net/issues/44817

**Comment by philon-msft** [comment]
Thanks all for reporting this. The next release of this package (coming soon) will use Azure.Identity 1.12.1 (or newer). If I understand correctly, that will fix the issue.

**Comment by anhhnguyen206** [comment]
@philon-msft Hi, is there an ETA for the next release? I'm looking to soon integrate this into my project and wonder if this bug has been fixed.

**Comment by philon-msft** [comment]
The next release should come out next week

**Comment by anhhnguyen206** [comment]
@philon-msft thank you very much for the prompt response!

**Comment by philon-msft** [comment]
v3.2.0 referencing Azure.Identity 1.13.1 has been released
