### ISSUE TITLE
Authentication with User Info

### ISSUE THREAD

**Issue by n-y-kim** [Azure/Microsoft.Azure.StackExchangeRedis#8]
Will this library support user based authorization beside service principal and managed identity?
For example, adding user as a memeber 

![image](https://github.com/Azure/Microsoft.Azure.StackExchangeRedis/assets/76769919/2bf8629e-21a6-45a2-b3d8-ce94ad18d3b2)

and access with the user name as the managed identity access in the sample project.

**Comment by philon-msft** [comment]
Yes I believe you can authenticate with a user the same way as you'd use a service principal. @samsaha-ms, can you confirm?

**Comment by samsaha-ms** [comment]
No, this library does not support user principal at present, we recommend using service principal for scenarios where opting for managed identity is not possible for applications.
In case you want to use user principal, you can use azure clients like azure cli or PowerShell to get the token and send the token in form of `AUTH <user principal object id> <user principal token>` using any redis client.
For example, with azure cli following is the command to get the token for your user principal.
`az login # It will open browser use the corresponding user principal email and password to login to Azure`
`az account get-access-token --resource acca5fbb-b7e4-4009-81f1-37e38fd66d78 --query "accessToken" --output tsv`

**Comment by n-y-kim** [comment]
Thank you for the fast replies! 😄 

@samsaha-ms, your suggestion was very successful and made this preview data access configuration by user too.
I think `AUTH` with user id & token should also be stated in the document. Will make a suggestion at the document repo.
