### ISSUE TITLE
ConfigurationOptions.ConfigureForAzureWithSystemAssignedManagedIdentityAsync Times out

### ISSUE THREAD

**Issue by RajeshPatelSH** [Azure/Microsoft.Azure.StackExchangeRedis#9]
Hi, 

I am trying to authenticate a connection to our Azure Cache for Redis instance. I am using the  ConfigureForAzureWithSystemAssignedManagedIdentityAsync method and passing in the principal Id of "dfa4d3a0-612f-419e-b547-7039cdc60eb3", however, the method times out after some time. This is the error message. 

`
System.AggregateException: 'One or more errors occurred. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (169.254.169.254:80))'
`

I am using version 1.1.0

**Comment by lsannicolas** [comment]
Just double checking, but it looks like its failing before you establish a connection and not when reauthenticating with a new token, correct?

And could you also update with the following:
1. Are you running this in an Azure VM?
2. Are you using the "Username" value in the Data Access Configuration section?

**Comment by RajeshPatelSH** [comment]
I apologize, I realized I used the wrong principalId. Thank you for the help
